version: '3'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'database'
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_TCP_PORT: 3307
    env_file:
      - '.env'
    networks:
      - 'api'
    volumes:
      - database
    ports:
      - '3307:3307'
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 100

  api:
    image: 'api:latest'
    container_name: 'api'
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - './src/:/app/src'
    ports:
      - '3000:5000'
    restart: 'always'
    networks:
      - 'api'
    env_file:
      - '.env'
    depends_on:
      mysql:
        condition: service_healthy

networks:
  api:

volumes:
  database:
